apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storage-operator.cfy.cz/storage-type: nfs
  name: nfs
provisioner: storage-operator.cfy.cz/awx
parameters:
  job_template_id: "105"
  hosts: "tvlsnfs01.pmb.cz"
mountOptions:
  - nfsvers=4
  - hard
  - intr
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
