apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storage-operator.cfy.cz/storage-type: nfs
  name: nfs
provisioner: kubernetes.io/no-provisioner
mountOptions:
  - nfsvers=4
  - hard
  - intr
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
