---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - storage.cfy.cz
  resources:
  - nfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.cfy.cz
  resources:
  - nfs/finalizers
  verbs:
  - update
- apiGroups:
  - storage.cfy.cz
  resources:
  - nfs/status
  verbs:
  - get
  - patch
  - update
