---
# vars file for provisioning_nfs_export

k8s: "{{ awx_openshift | default(role_provisioning_nfs_export_k8s) }}"
cluster_name: "{{ awx_cluster_name | default(role_provisioning_nfs_export_cluster_name) }}"
namespace_name: "{{ awx_namespace_name | default(role_provisioning_nfs_export_namespace_name) }}"
pvc_name: "{{ awx_pvc_name | default(role_provisioning_nfs_export_pvc_name) }}"
lv_prefix: "{{ awx_lv_prefix | default(role_provisioning_nfs_export_lv_prefix) }}"
vg_name: "{{ awx_vg_name | default(role_provisioning_nfs_export_vg_name) }}"
lv_name: "{{ awx_lv_name | default(role_provisioning_nfs_export_lv_name) }}"
lv_size: "{{ awx_lv_size | default(role_provisioning_nfs_export_lv_size) }}"
mount_path: "{{ awx_mount_path | default(role_provisioning_nfs_export_mount_path) }}"
fs_type: "{{ awx_fs_type | default(role_provisioning_nfs_export_fs_type) }}"
fs_resize: "{{ awx_resize_fs | default(role_provisioning_nfs_export_fs_resize) }}"
export_cidr: "{{ awx_export_cidr | default(role_provisioning_nfs_export_export_cidr) }}"
